### ISSUE TITLE
🐛 MongoDB Container in Restart Loop (mongo:7-jammy)

### ISSUE THREAD

**Issue by mohamedabdallah1996** [mohamedabdallah1996/mini-rag-app#1]
## Description
When running the mongodb service using the `mongo:7-jammy` image in Docker Compose, the container repeatedly enters a restart loop. It starts, encounters a storage-related error, crashes, and is then restarted by Docker.

This happens when using a bind mount for the data directory (e.g., `./mongodb:/data/db`).

## Relevant docker-compose.yaml Snippet

```yaml
services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    networks:
      - backend
    restart: always
```

## Observed Logs
```
WiredTiger error message: open: File exists
WiredTiger.wt found, renamed to WiredTiger.wt.28
Operation not permitted
Failed to start up WiredTiger under any compatibility version.
Terminating. reason: 1: Operation not permitted
Fatal assertion
```

## 🔍 Root Cause
This issue is caused by one or more of the following:

**Permission issues**: MongoDB inside the container (user ID 999) lacks permissions to read/write the bind-mounted host folder (`./mongodb`).

**Storage format conflict**: The existing `./mongodb` data directory may contain data from another MongoDB version, causing incompatibilities with MongoDB 7.

**Unsupported downgrade**: If previous data was written using a newer version, MongoDB cannot safely downgrade and load that data.

**Comment by mohamedabdallah1996** [comment]
## ✅ Solutions
### 🧼 Option 1: Clean and Fix Permissions (if data loss is acceptable)

If you're okay with losing existing local data:

```bash
docker compose down -v
rm -rf ./mongodb
mkdir -p ./mongodb
sudo chown -R 999:999 ./mongodb
docker compose up --build
```

This ensures MongoDB has permission to access the folder and starts fresh.

### 📦 Option 2: Switch to Named Volume (Recommended)
Change the volumes: section to use a named volume instead of a bind mount:

```yaml
services:
  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend
    restart: always

volumes:
  mongodb_data:
```

Then reset and restart:
```yaml
docker compose down -v
docker compose up --build -d
```

This approach avoids host file system issues and lets Docker handle volume management.

## 📌 Recommendation
For database services like MongoDB, use named volumes in production or long-term development. Bind mounts are better suited for development of source code, not data directories requiring strict permissions and stability.
